- hosts: all
  become: true
  tasks:
      - ping:

- name: Sample playbook
  hosts: all
  tasks:
      - name: Print hello world
        ansible.builtin.debug:
            msg: HelloWorld

      - name: Update MongoDB Conf file
        ansible.builtin.replace:
          path: /tmp/example.txt
          regexp: '127.0.0.1'
          replace: '0.0.0.0'
          firstmatch: yes
          state: present