- hosts: all
  become: true
  tasks:
      - ping:

- name: Sample playbook
  hosts: all
  tasks:
      - name: Print hello world
        ansible.builtin.debug:
            msg: HelloWorld

  #    - name: Read the content of the file
  #      slurp:
  #          src: /tmp/example.txt  # Replace with the path to your file
  #      register: file_content

      - name: Update MongoDB Conf file
        lineinfile:
          path: /tmp/example.txt
          regexp: '127.0.0.1'
          line: '0.0.0.0'
          firstmatch: yes
          state: present