- name: Demo on Variables
  hosts: localhost
  vars:
    URL: vars.google.com
   vars_files:
     - sample-vars.yml
   tasks:
     - name Print URL
     - ansible.builtin.debug:
         msg: "URL - {{ URL }}, URL1 - {{ URL1 }}"
