- name: test
  hosts: all
  become: true

- name: Replace the first occurrence of old_string with new_string
  ansible.builtin.replace:
    path: /tmp/example.txt  # Replace with the path to your file
    regexp: 'old_string'
    replace: 'new_string'
    count: 1  # Replace only the first occurrence

    # Check if the file has been modified
    #when: "'old_string' in file_content.content | b64decode"

